### ISSUE TITLE
Visibility inside sequence of narrow and wide dependencies stage 

### ISSUE THREAD

**Issue by tenstriker** [hammerlab/spree#60]
I am evaluating spree to monitor our spark application and I am specifically interested in pin pointing specific transformation when a Stage failed. As stage in spark can be sequence of multiple transformation its really hard to find root cause when stage fails. We can certainly get some idea from executor logs but its not straightforward most of the time. Second use case is it can help us optimize particular transformation from our end when we notice that Stage is performing poorly. Thanks

**Comment by ryan-williams** [comment]
In general, I don't think it's well-defined to isolate one transformation within a stage as causing a failure; if you are getting exceptions that point to one of a few `.map` closures, then that gives you your answer, but if you are e.g. failing due to memory issues, all the transformations in a given stage are likely playing some part in that.

Unfortunately, when apps are failing, Spree is never going to be a substitute for looking in the executor logs, though it can hopefully help you generate leads more quickly about what to look for in the logs, understand which failures are likely to blow over and which are going to fail a stage or app, etc.

Let me know if that doesn't make sense or you have further questions!

**Comment by ryan-williams** [comment]
(to your second comment, about optimizing poorly-performing stages, I think Spree can definitely help you see the progression of various executor- and task-level stats over their lifetimes, which I've found very useful for understanding my apps' performance)

**Comment by ryan-williams** [comment]
I just filed #62 which addresses one way of understanding narrow/wide stage RDD deps like the Spark UI allows.
